server:
  port: 9002
spring:
  application:
    name: user-server
  cloud:
    consul:
      host: localhost
      port: 8500
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user-server?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.hjt.client.dao : debug
